// client/src/app/blog/[postSlug]/page.tsx
import { env } from '@/env/client.mjs'
import { getData } from '@/utils/api.utils'
import Image from 'next/image'
import ReactMarkdown from 'react-markdown'

type GetData = {
    data: Post
    meta: Meta
}

interface PostSlugProps {
    params: {
        postSlug: string
    }
}

const PostSlug = async ({ params: { postSlug } }: PostSlugProps) => {
    const postId = postSlug.substring(0, postSlug.indexOf('--'))

    if (!postId) {
        return null
    }

    const post = await getData<GetData>(`/posts/${postId}?`, {
        populate: '*',
    })

    const { title, content, image } = post.data.attributes

    return (
        <div className="flex w-full flex-col">
            <Image
                src={`${env.NEXT_PUBLIC_SERVER_ADDRESS}${image.data.attributes.url}`}
                height={image.data.attributes.height}
                width={image.data.attributes.width}
                alt={image.data.attributes.caption || ''}
            />
            <div className="prose mx-auto mt-4 flex max-w-3xl flex-col">
                <h1>{title}</h1>
                <ReactMarkdown children={content || ''} />
            </div>
        </div>
    )
}

export default PostSlug

// client/pages/blog/[postSlug].vue
<template>
    <article class="container mx-auto pb-10">
        <div v-if="post" class="prose-xl lg:w-3/4 prose-headings:mb-2 prose-headings:leading-snug prose-p:tracking-tight prose-p:leading-normal prose-li:tracking-tight prose-li:leading-normal prose-h1:heading  mx-auto">
        <NuxtImg :src="`https://strapi.titanizo.pl${post.data.attributes.image.data.attributes.formats.large.url}`" class="aspect-16/9 object-cover w-full" />
            <h1>{{ post.data.attributes.title }}</h1>
            <div v-html="$mdRenderer.render(post.data.attributes.content)" />
        </div>
    </article>
</template>

<script setup lang="ts">
const { params } = useRoute();
const postSlug = params.postSlug as string;
const postId = postSlug.substring(0, postSlug.indexOf('--'))
if(!postId) throw createError({ statusCode: 404, message: 'Nieprawidłowy URL postu!' })

type GetPost = {
    data: Post
    meta: Meta
}
const {data: post, error } = await useGetApi<GetPost>(`/posts/${postId}`, {
    populate: '*',
})

if(!post.value) throw createError({ ...error.value })

useHead({
    title: post.value?.data.attributes.title
})



</script>
