// client/components/Navbar/index.vue
<template>
  <nav class="z-10 sticky top-0">
    <section class="w-full py-3 text-center uppercase tracking-tight font-medium text-sm bg-neutral-900 text-white ">
      <div class="container mx-auto flex w-full justify-between">
        <span class="tracking-tighter w-full sm:w-auto"><font-awesome-icon size="lg" class="mr-2" icon="fa-light fa-truck-fast" />Darmowa dostawa od 499 ZŁ dla zalogowanych</span>
        <div class="flex-grow-1 hidden sm:block" />
        <aside class="gap-6 hidden sm:flex">
          <nuxt-link to="/blog">
            Blog
          </nuxt-link>
          <div>Inspiracje</div>
          <div>Kontakt</div>
        </aside>
      </div>
    </section>
    <nav class="w-full min-h-36 bg-white shadow-md">
      <section class="container mx-auto py-5 flex flex-row w-full justify-between">
        <nuxt-link to="/" class="md:mr-10">
          <nuxt-img src="/assets/brand/default.svg" alt="Logo Titanizo - Dom i ogród" class="h-10 " />
        </nuxt-link>
        <label for="search" class="relative w-full hidden md:block">
          <font-awesome-icon icon="fa-light fa-magnifying-glass" class="absolute top-1/2 -translate-y-1/2 left-4" />
          <input id="search" type="text" placeholder="Szukaj w Titanizo..." class="w-full bg-neutral-100 rounded-full px-10 py-3 placeholder:text-neutral-900 tracking-tight">
        </label>
        <div class="md:ml-16 flex items-center">
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-user" />
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-heart" />
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-bag-shopping" />
        </div>
      </section>

      <section class="container mx-auto flex flex-row w-full gap-6 text-sm">
        <nuxt-link v-for="category in categories" :key="category.id" :to="`/kategoria/${category.id}--${slugify(category.attributes.name, { lower: true })}`" class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          {{ category.attributes.name }}
          <font-awesome-icon icon="fa-light fa-chevron-down" />
        </nuxt-link>
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          Promocje
        </div>
        <div class="flex-1" />
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          Nowości
        </div>
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          <font-awesome-icon icon="fa-duotone fa-fire" size="lg" class="text-rose-700" />
          Bestsellery
        </div>
      </section>
    </nav>
  </nav>
</template>

<script setup lang="ts">
import slugify from 'slugify'

type GetCategories = {
    data: Category[]
    meta: Meta
}

const response = await useGetApi<GetCategories>('/categories', {
    'filters[parent][id][$null]': 'true',
    'populate[0]': 'categories',
    'populate[1]': 'categories.categories',
})

const categories = response.data.value?.data

</script>

// client/src/components/Navbar/Navbar.tsx
import Link from 'next/link'
import { MENU_ICONS } from './constant'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import slugify from 'slugify'
import { getData } from '@/utils/api.utils'

type GetData = {
    data: Category[]
    meta: Meta
}

export const Navbar = async () => {
    const response = await getData<GetData>('/categories?populate=*')

    return (
        <nav className="sticky top-0 z-10 flex w-full flex-col bg-black text-white">
            <div className="flex items-center border-b border-white/20 px-6 py-2">
                <span className="text-sm">
                    Darmowa dostawa zamówień od 500 PLN!
                </span>
                <div className="flex flex-grow"></div>
                <a
                    href="tel: +48 883 705 815"
                    className="mr-3 font-medium tracking-tighter"
                >
                    <FontAwesomeIcon
                        icon={faPhoneVolume}
                        className="mr-2 text-white/50"
                    />
                    883 705 815
                </a>
                <small className="text-white/80">9:00 - 19:00</small>
            </div>
            <div className="relative flex min-h-[60px] w-full items-center bg-black px-6">
                <Link href="/">
                    <img
                        src="https://deante.pl/brand/white.svg"
                        alt="Logo Deante"
                        width={120}
                        height={30}
                    />
                </Link>
                <div className="z-20 flex h-[60px] flex-row items-center">
                    {response.data.map((category) => (
                        <div
                            key={category.id}
                            className="group flex h-full items-center"
                        >
                            <Link
                                className="mx-4 uppercase transition-colors hover:text-white"
                                href={`/${category.id}--${slugify(
                                    category.attributes.name
                                )}`}
                            >
                                {category.attributes.name}
                            </Link>
                            <div className="absolute left-0 top-[60px] hidden min-h-[40vh] w-full bg-black/40 group-hover:block">
                                {category.attributes.subcategories.data.map(
                                    (subcategories) => (
                                        <Link
                                            key={subcategories.id}
                                            href={`/${category.id}--${slugify(
                                                category.attributes.name
                                            )}/${subcategories.id}--${slugify(
                                                subcategories.attributes.name
                                            )}`}
                                        >
                                            {subcategories.attributes.name}
                                        </Link>
                                    )
                                )}
                            </div>
                        </div>
                    ))}
                </div>
                <div className="flex flex-1 flex-row-reverse items-center">
                    {MENU_ICONS.map(({ name, href, icon }) => (
                        <Link
                            className="p-2 text-white/75 transition-colors hover:text-white"
                            href={href}
                            key={name}
                        >
                            <FontAwesomeIcon
                                icon={icon}
                                className="text-white"
                            ></FontAwesomeIcon>
                        </Link>
                    ))}
                </div>
            </div>
        </nav>
    )
}
