// client/components/Navbar/index.vue
<template>
  <nav class="sticky top-0 z-20">
    <section class="w-full py-3 text-center uppercase tracking-tight font-medium text-sm bg-neutral-900 text-white ">
      <div class="container mx-auto flex w-full justify-between items-center">
        <span class="tracking-tighter w-full sm:w-auto text-xs"><font-awesome-icon size="lg" class="mr-2" icon="fa-light fa-truck-fast" />Darmowa dostawa zakupów powyżej 499 ZŁ</span>
        <div class="flex-grow-1 hidden sm:block" />
        <aside class="gap-6 hidden sm:flex">
          <nuxt-link to="/blog">
            Blog
          </nuxt-link>
          <div>Inspiracje</div>
          <div>Kontakt</div>
        </aside>
      </div>
    </section>
    <nav class="w-full min-h-36 bg-white shadow-md">
      <section class="container mx-auto py-5 flex flex-row w-full justify-between" @mouseover="mainCategory = null">
        <nuxt-link to="/" class="md:mr-10">
          <nuxt-img loading="lazy" src="/assets/brand/default.svg" alt="Logo Titanizo - Dom i ogród" class="h-10 " />
        </nuxt-link>
        <label for="search" class="relative w-full hidden md:block">
          <font-awesome-icon icon="fa-light fa-magnifying-glass" class="absolute top-1/2 -translate-y-1/2 left-4" />
          <input id="search" type="text" placeholder="Szukaj w Titanizo..." class="w-full bg-neutral-100 rounded-full px-10 py-3 placeholder:text-neutral-900 tracking-tight">
        </label>
        <div class="md:ml-16 flex items-center">
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-user" />
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-heart" />
          <font-awesome-icon size="xl" class="ml-5" icon="fa-light fa-bag-shopping" />
        </div>
      </section>

      <section class="container mx-auto flex flex-row w-full gap-6 text-sm">
        <template v-if="categories?.data">
          <nuxt-link
            v-for="category in categories.data"
            :key="category.id"
            :to="`/kategoria/${category.id}--${slugify(category.attributes.name, { lower: true })}`"
            class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700"
            :class="{ 'text-rose-700': mainCategory === category}"
            @mouseover="mainCategory = category; mainCategory.attributes.categories?.data.length ? subCategory = mainCategory.attributes.categories.data[0] : false"
          >
            {{ category.attributes.name }}
            <font-awesome-icon icon="fa-light fa-chevron-down" />
          </nuxt-link>
        </template>
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          Promocje
        </div>
        <div class="flex-1" />
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          Nowości
        </div>
        <div class="pt-4 pb-3 cursor-pointer transition-colors uppercase font-medium border-b-[3px] border-transparent hover:border-rose-700 hover:text-rose-700">
          <font-awesome-icon icon="fa-duotone fa-fire" size="lg" class="text-rose-700" />
          Bestsellery
        </div>
      </section>
    </nav>

    <transition>
      <nav v-if="mainCategory" class="bg-white fixed container mx-auto left-1/2 -translate-x-1/2 rounded-b" @mouseleave="mainCategory = null">
        <div v-if="mainCategory.attributes.categories?.data" class="flex">
          <aside class="bg-neutral-100 rounded-bl w-1/5 py-4">
            <nuxt-link
              v-for="subcategory in mainCategory.attributes.categories.data"
              :key="subcategory.id"
              class="p-3 hover:text-rose-700 transition-colors text-sm flex justify-between items-center gap-10 tracking-tight cursor-pointer"
              :class="{'bg-white text-rose-600': subCategory === subcategory}"
              :to="`/kategoria/${subcategory.id}--${slugify(subcategory.attributes.name, { lower: true })}`"
              @mouseover="subcategory.attributes.categories?.data.length ? subCategory = subcategory : false"
            >
              <span>{{ subcategory.attributes.name }}</span>
              <font-awesome-icon :icon="`fa-light ${subcategory.attributes.categories?.data.length ? 'fa-chevron-right' : 'fa-arrow-up-right-from-square'}`" size="sm" />
            </nuxt-link>
          </aside>
          <section v-if="subCategory?.attributes.categories?.data" class="w-4/5 p-5">
            <nav>
              <ul>
                <li v-for="lowCategory in subCategory?.attributes.categories.data" :key="lowCategory.id" class="py-1 text-sm tracking-tight hover:text-rose-600 cursor-pointer">
                  <nuxt-link :to="`/kategoria/${lowCategory.id}--${slugify(lowCategory.attributes.name, { lower: true })}`">
                    {{ lowCategory.attributes.name }}
                  </nuxt-link>
                </li>
              </ul>
            </nav>
          </section>
        </div>
      </nav>
    </transition>
  </nav>
  <transition>
    <div v-if="mainCategory" class="fixed inset-0 bg-black/60 backdrop-blur z-10" />
  </transition>
</template>

<script setup lang="ts">
import slugify from 'slugify'

type GetCategories = {
    data: Category[]
    meta: Meta
}

const { data: categories, } = await useGetApi<GetCategories>('/categories', {
    'filters[parent][id][$null]': 'true',
    'populate[0]': 'categories',
    'populate[1]': 'categories.categories',
})

const mainCategory = ref<null|Category>(null)
const subCategory = ref<null|Category>(null)

</script>

<style scoped>
.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}

</style>

// _next/src/components/Navbar/Navbar.tsx
import Link from 'next/link'
import { MENU_ICONS } from './constant'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import { getAPI } from '@/utils/api.utils'
import { transformObjectToPathname } from '@/utils/api.utils'
import NavbarIconBag from './NavbarIcons/NavbarIconBag'
import { MENU } from './Navbar.constants'
import { env } from '@/env/client.mjs'
// import { NavbarProfileButton } from './NavbarProfileButton/NavbarProfileButton'
import { WrappedImage } from '../WrappedImage'

type GetData = {
    data: Category[]
    meta: Meta
}

export const Navbar = async () => {
    const response = await getAPI<GetData>(
        '/categories?populate[0]=subcategories'
    )

    const data = response.data.map((response) => ({
        ...response,
        attributes: {
            ...response.attributes,
            subcategories: {
                ...response.attributes.subcategories,
                data: response.attributes.subcategories.data.sort((a, b) =>
                    a.attributes.name.localeCompare(b.attributes.name)
                ),
            },
        },
    }))

    return (
        <nav>
            <div className="container fixed left-1/2 top-0 z-10 flex w-full translate-x-[-50%] flex-col text-white">
                <div className="flex items-center border-b border-white/20 bg-black px-6 py-2">
                    <span className="text-sm">
                        Darmowa dostawa zamówień powyżej 500 PLN!
                    </span>
                    <div className="flex flex-grow"></div>
                    <a
                        href="tel: +48 883 705 815"
                        className="mr-3 font-medium tracking-tighter"
                    >
                        <FontAwesomeIcon
                            icon={faPhoneVolume}
                            className="mr-2 text-white/50"
                        />
                        883 705 815
                    </a>
                    <small className="text-white/80">9:00 - 19:00</small>
                </div>
                <div className="relative flex min-h-[60px] w-full items-center bg-black/50  px-6 backdrop-blur">
                    <Link href="/">
                        <WrappedImage
                            src={env.NEXT_PUBLIC_BRAND_LOGO_URL}
                            alt="Logo Deante"
                            width={120}
                            height={30}
                        />
                    </Link>
                    <div className="z-20 flex h-[60px] flex-row items-center">
                        {data.map((category) => (
                            <div
                                key={category.id}
                                className="group/main flex h-full items-center"
                            >
                                <Link
                                    href={transformObjectToPathname(category)}
                                    className="mx-4 cursor-pointer uppercase transition-colors hover:text-white h-[60px] leading-[60px] z-50"
                                >
                                    {category.attributes.name}
                                </Link>
                                <div className="absolute left-0 top-[60px] hidden min-h-[40vh] w-full flex-row bg-black/80 group-hover/main:flex">
                                    <div className="grid flex-1 grid-cols-5 p-6">
                                        {category.attributes.subcategories.data.map(
                                            (subcategory) => (
                                                <div key={subcategory.id}>
                                                    <Link
                                                        key={subcategory.id}
                                                        href={`${transformObjectToPathname(
                                                            category
                                                        )}${transformObjectToPathname(
                                                            subcategory
                                                        )}`}
                                                    >
                                                        {
                                                            subcategory
                                                                .attributes.name
                                                        }
                                                    </Link>
                                                </div>
                                            )
                                        )}
                                    </div>
                                </div>
                            </div>
                        ))}
                        {MENU.map(({ id, name, href }) => (
                            <Link
                                key={id}
                                href={href}
                                className="mx-4 cursor-pointer uppercase transition-colors hover:text-white h-[60px] leading-[60px] z-50"
                            >
                                {name}
                            </Link>
                        ))}
                        {/* <NavbarProfileButton /> */}
                    </div>
                    <div className="flex flex-1 flex-row-reverse items-center">
                        <NavbarIconBag />
                        {MENU_ICONS.map(({ name, href, icon }) => (
                            <Link
                                className="p-2 text-white/75 transition-colors hover:text-white"
                                href={href}
                                key={name}
                            >
                                <FontAwesomeIcon
                                    icon={icon}
                                    className="text-white"
                                ></FontAwesomeIcon>
                            </Link>
                        ))}
                    </div>
                </div>
            </div>
        </nav>
    )
}
